"""Train the ANN sentence classifier for ML-based Minutes of Meeting.

Purpose:
    Train ``SentenceClassifierANN`` on the processed master annotation dataset
    using embeddings generated by ``EmbeddingService``.

Responsibilities:
    - Load and validate ``datasets/processed/master_dataset.csv``.
    - Ignore invalid rows safely through ``TrainingDatasetManager``.
    - Generate sentence embeddings with the existing embedding service.
    - Train the existing PyTorch ANN classifier.
    - Track validation metrics and save only the best-performing model.
    - Save label mapping, training metrics, and a confusion matrix image.

Inputs:
    ``datasets/processed/master_dataset.csv``.

Outputs:
    - ``datasets/models/best_model.pt``
    - ``datasets/models/label_mapping.json``
    - ``datasets/models/training_metrics.json``
    - ``datasets/models/confusion_matrix.png``

Safety:
    This script is an offline training utility. It is not imported by the
    production Streamlit app, workflow, exports, email, or SMTP path.
"""

from __future__ import annotations

from dataclasses import asdict
import csv
import json
import os
from pathlib import Path
import random
import sys
import tempfile
from typing import Any

import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

try:
    from ml_mom.ann_model import SentenceClassifierANN
    from ml_mom.embeddings import EmbeddingService
    from ml_mom.feature_extraction import SentenceFeature
    from ml_mom.training_dataset import (
        LABEL_TO_ID,
        REQUIRED_COLUMNS,
        PreparedTrainingDataset,
        TrainingDatasetManager,
        TrainingSample,
    )
except ModuleNotFoundError:  # pragma: no cover - supports direct script execution.
    from ann_model import SentenceClassifierANN
    from embeddings import EmbeddingService
    from feature_extraction import SentenceFeature
    from training_dataset import (
        LABEL_TO_ID,
        REQUIRED_COLUMNS,
        PreparedTrainingDataset,
        TrainingDatasetManager,
        TrainingSample,
    )


MASTER_DATASET_PATH = Path("datasets") / "processed" / "master_dataset.csv"
MODEL_DIR = Path("datasets") / "models"
BEST_MODEL_PATH = MODEL_DIR / "best_model.pt"
LABEL_MAPPING_PATH = MODEL_DIR / "label_mapping.json"
TRAINING_METRICS_PATH = MODEL_DIR / "training_metrics.json"
CONFUSION_MATRIX_PATH = MODEL_DIR / "confusion_matrix.png"

BATCH_SIZE = 16
EPOCHS = 50
LEARNING_RATE = 0.001
VALIDATION_RATIO = 0.20
PATIENCE = 5
RANDOM_SEED = 42


def normalize_master_dataset_for_manager(source_path: Path) -> Path | None:
    """Create a temporary CSV compatible with ``TrainingDatasetManager``.

    Args:
        source_path: Master dataset CSV path.

    Returns:
        Temporary normalized CSV path, or ``None`` when the source cannot be
        read.
    """

    if not source_path.exists():
        print(f"Dataset not found: {source_path}")
        return None

    try:
        with source_path.open("r", newline="", encoding="utf-8") as source_file:
            reader = csv.DictReader(source_file)
            rows = [dict(row) for row in reader]
    except Exception as exc:
        print(f"Dataset could not be read safely: {exc}")
        return None

    fieldnames = list(REQUIRED_COLUMNS)
    temp_dir = Path(tempfile.gettempdir()) / "meetscribe_ann_training"
    temp_dir.mkdir(parents=True, exist_ok=True)
    normalized_path = temp_dir / "normalized_master_dataset.csv"

    # The current annotation app does not emit cluster_id, but the shared
    # dataset manager requires it. Adding an empty optional field here lets the
    # existing validation and label-encoding module remain the source of truth.
    with normalized_path.open("w", newline="", encoding="utf-8") as output_file:
        writer = csv.DictWriter(output_file, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            normalized_row = {column: row.get(column, "") for column in fieldnames}
            writer.writerow(normalized_row)

    return normalized_path


def load_prepared_dataset(master_dataset_path: Path) -> PreparedTrainingDataset | None:
    """Load, validate, clean, encode, and split the master dataset.

    Args:
        master_dataset_path: Path to processed master CSV.

    Returns:
        Prepared training dataset, or ``None`` when no usable samples exist.
    """

    normalized_path = normalize_master_dataset_for_manager(master_dataset_path)
    if normalized_path is None:
        return None

    manager = TrainingDatasetManager(
        train_ratio=1.0 - VALIDATION_RATIO,
        validation_ratio=VALIDATION_RATIO,
        test_ratio=0.0,
        random_seed=RANDOM_SEED,
    )
    prepared = manager.prepare_from_csv(normalized_path)
    print_dataset_statistics(prepared)

    if prepared.validation_messages:
        print("Dataset validation messages:")
        for message in prepared.validation_messages:
            print(f"- {message}")

    if not prepared.samples:
        print("No valid labeled samples are available for training.")
        return None
    if not prepared.train_samples or not prepared.validation_samples:
        print("Dataset is too small to create both training and validation splits.")
        return None

    return prepared


def print_dataset_statistics(prepared: PreparedTrainingDataset) -> None:
    """Print dataset statistics before training.

    Args:
        prepared: Prepared dataset from ``TrainingDatasetManager``.
    """

    print("Dataset statistics")
    print(json.dumps(prepared.statistics, indent=2))
    print("Label mapping")
    print(json.dumps(prepared.label_mapping, indent=2))


def sample_to_sentence_feature(sample: TrainingSample) -> SentenceFeature:
    """Convert a training sample into the feature shape expected by embeddings.

    Args:
        sample: Cleaned labeled training sample.

    Returns:
        Minimal ``SentenceFeature`` containing sentence identity and text.
    """

    words = sample.sentence.split()
    average_word_length = (
        sum(len(word) for word in words) / len(words) if words else 0.0
    )
    return SentenceFeature(
        sentence_id=sample.sentence_id,
        turn_id=sample.turn_id,
        speaker=sample.speaker,
        timestamp=sample.timestamp,
        original_sentence=sample.sentence,
        word_count=len(words),
        character_count=len(sample.sentence),
        average_word_length=round(average_word_length, 3),
        sentence_position=sample.sentence_id,
        is_question=sample.sentence.rstrip().endswith("?"),
        is_exclamation="!" in sample.sentence,
        contains_number=any(char.isdigit() for char in sample.sentence),
        contains_currency=False,
        contains_percentage="%" in sample.sentence,
        contains_date=False,
        contains_time=False,
        contains_action_keyword=False,
        contains_decision_keyword=False,
        contains_discussion_keyword=False,
        contains_deadline_keyword=False,
        speaker_name=sample.speaker,
        speaker_turn_index=1,
        previous_sentence=None,
        next_sentence=None,
    )


def generate_tensors(
    samples: list[TrainingSample],
    embedding_service: EmbeddingService,
    split_name: str,
) -> tuple[torch.Tensor, torch.Tensor] | None:
    """Generate embedding and label tensors for training.

    Args:
        samples: Training samples to embed.
        embedding_service: Existing embedding service.
        split_name: Name printed for diagnostics.

    Returns:
        Tuple of embedding tensor and label tensor, or ``None`` if embeddings
        are unavailable.
    """

    sentence_features = [sample_to_sentence_feature(sample) for sample in samples]
    embedding_result = embedding_service.generate_embeddings(sentence_features)
    if embedding_result.error_message:
        print(embedding_result.error_message)
        return None

    vectors: list[list[float]] = []
    labels: list[int] = []
    for sample, embedding in zip(samples, embedding_result.embeddings):
        if not embedding.embedding_vector:
            print(f"Skipping sentence {sample.sentence_id}: empty embedding.")
            continue
        vectors.append(embedding.embedding_vector)
        labels.append(sample.label_id)

    if not vectors:
        print("No valid embeddings were generated.")
        return None

    feature_tensor = torch.tensor(vectors, dtype=torch.float32)
    label_tensor = torch.tensor(labels, dtype=torch.long)
    print(f"{split_name} embeddings generated: {feature_tensor.size(0)}")
    print(f"{split_name} embedding tensor shape: {tuple(feature_tensor.shape)}")
    return (
        feature_tensor,
        label_tensor,
    )


def verify_embedding_model(embedding_service: EmbeddingService) -> int | None:
    """Load and verify the configured embedding model before training.

    Args:
        embedding_service: Existing embedding service.

    Returns:
        Embedding dimension when the model is usable; otherwise ``None``.
    """

    load_error = embedding_service.load_model()
    if load_error:
        print(load_error)
        return None

    embedding_dimension = embedding_service.get_embedding_dimension()
    if embedding_dimension is None:
        print(embedding_service.error_message or "Embedding dimension is unavailable.")
        return None

    # These diagnostics prove the SentenceTransformers integration is working
    # before we spend time preparing tensors and entering the training loop.
    print(f"embedding model loaded: {embedding_service.model_name}")
    print(f"embedding dimension: {embedding_dimension}")
    return embedding_dimension


def create_data_loader(
    features: torch.Tensor,
    labels: torch.Tensor,
    shuffle: bool,
) -> DataLoader:
    """Create a PyTorch data loader.

    Args:
        features: Embedding tensor.
        labels: Label tensor.
        shuffle: Whether to shuffle batches.

    Returns:
        DataLoader for training or validation.
    """

    dataset = TensorDataset(features, labels)
    return DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=shuffle)


def compute_metrics(
    predictions: list[int],
    targets: list[int],
    class_count: int,
) -> dict[str, float | list[list[int]]]:
    """Compute accuracy, macro precision, recall, F1, and confusion matrix.

    Args:
        predictions: Predicted label IDs.
        targets: Ground-truth label IDs.
        class_count: Number of supported classes.

    Returns:
        Metrics dictionary.
    """

    confusion = [[0 for _ in range(class_count)] for _ in range(class_count)]
    for target, prediction in zip(targets, predictions):
        if 0 <= target < class_count and 0 <= prediction < class_count:
            confusion[target][prediction] += 1

    correct = sum(confusion[index][index] for index in range(class_count))
    total = sum(sum(row) for row in confusion)
    accuracy = correct / total if total else 0.0

    precision_values: list[float] = []
    recall_values: list[float] = []
    f1_values: list[float] = []
    for index in range(class_count):
        true_positive = confusion[index][index]
        false_positive = sum(confusion[row][index] for row in range(class_count)) - true_positive
        false_negative = sum(confusion[index]) - true_positive
        precision = (
            true_positive / (true_positive + false_positive)
            if true_positive + false_positive
            else 0.0
        )
        recall = (
            true_positive / (true_positive + false_negative)
            if true_positive + false_negative
            else 0.0
        )
        f1 = (
            2 * precision * recall / (precision + recall)
            if precision + recall
            else 0.0
        )
        precision_values.append(precision)
        recall_values.append(recall)
        f1_values.append(f1)

    return {
        "accuracy": accuracy,
        "precision": sum(precision_values) / class_count,
        "recall": sum(recall_values) / class_count,
        "f1": sum(f1_values) / class_count,
        "confusion_matrix": confusion,
    }


def run_epoch(
    model: SentenceClassifierANN,
    data_loader: DataLoader,
    loss_fn: nn.Module,
    device: torch.device,
    optimizer: torch.optim.Optimizer | None = None,
) -> tuple[float, dict[str, float | list[list[int]]]]:
    """Run one training or validation epoch.

    Args:
        model: ANN classifier.
        data_loader: Batch loader.
        loss_fn: CrossEntropyLoss.
        device: CPU or CUDA device.
        optimizer: Adam optimizer for training. ``None`` runs validation.

    Returns:
        Average loss and metrics.
    """

    is_training = optimizer is not None
    model.train(is_training)
    total_loss = 0.0
    total_samples = 0
    predictions: list[int] = []
    targets: list[int] = []

    for batch_features, batch_labels in data_loader:
        batch_features = batch_features.to(device)
        batch_labels = batch_labels.to(device)

        if is_training:
            optimizer.zero_grad()

        logits = model(batch_features)
        if logits.numel() == 0:
            continue

        loss = loss_fn(logits, batch_labels)
        if is_training:
            loss.backward()
            optimizer.step()

        batch_size = batch_labels.size(0)
        total_loss += float(loss.item()) * batch_size
        total_samples += batch_size
        predictions.extend(torch.argmax(logits, dim=1).detach().cpu().tolist())
        targets.extend(batch_labels.detach().cpu().tolist())

    average_loss = total_loss / total_samples if total_samples else 0.0
    metrics = compute_metrics(predictions, targets, class_count=len(LABEL_TO_ID))
    return average_loss, metrics


def save_training_outputs(
    model: SentenceClassifierANN,
    label_mapping: dict[str, int],
    metrics_history: list[dict[str, Any]],
    confusion_matrix: list[list[int]],
) -> None:
    """Save the best model, label mapping, metrics, and confusion matrix image.

    Args:
        model: Best-performing model.
        label_mapping: Label-to-ID mapping.
        metrics_history: Per-epoch training metrics.
        confusion_matrix: Best validation confusion matrix.
    """

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), BEST_MODEL_PATH)
    LABEL_MAPPING_PATH.write_text(
        json.dumps(label_mapping, indent=2),
        encoding="utf-8",
    )
    TRAINING_METRICS_PATH.write_text(
        json.dumps(metrics_history, indent=2),
        encoding="utf-8",
    )
    save_confusion_matrix_png(confusion_matrix)


def save_confusion_matrix_png(confusion_matrix: list[list[int]]) -> None:
    """Save confusion matrix as a PNG image when matplotlib is available.

    Args:
        confusion_matrix: Confusion matrix values.
    """

    try:
        os.environ.setdefault("MPLCONFIGDIR", str(MODEL_DIR / "matplotlib_cache"))
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        labels = list(LABEL_TO_ID.keys())
        fig, axis = plt.subplots(figsize=(7, 6))
        image = axis.imshow(confusion_matrix, cmap="Blues")
        axis.set_xticks(range(len(labels)))
        axis.set_yticks(range(len(labels)))
        axis.set_xticklabels(labels, rotation=45, ha="right")
        axis.set_yticklabels(labels)
        axis.set_xlabel("Predicted")
        axis.set_ylabel("Actual")
        axis.set_title("Validation Confusion Matrix")
        for row_index, row in enumerate(confusion_matrix):
            for column_index, value in enumerate(row):
                axis.text(column_index, row_index, str(value), ha="center", va="center")
        fig.colorbar(image, ax=axis)
        fig.tight_layout()
        fig.savefig(CONFUSION_MATRIX_PATH)
        plt.close(fig)
        return
    except Exception as exc:
        print(f"Matplotlib confusion matrix save failed; using Pillow fallback. Details: {exc}")

    save_confusion_matrix_png_with_pillow(confusion_matrix)


def save_confusion_matrix_png_with_pillow(confusion_matrix: list[list[int]]) -> None:
    """Save a confusion matrix PNG without matplotlib.

    Args:
        confusion_matrix: Confusion matrix values.
    """

    from PIL import Image, ImageDraw

    labels = list(LABEL_TO_ID.keys())
    cell_size = 90
    label_width = 170
    title_height = 70
    width = label_width + cell_size * len(labels) + 20
    height = title_height + cell_size * len(labels) + 80
    max_value = max((max(row) for row in confusion_matrix), default=1) or 1

    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    draw.text((20, 20), "Validation Confusion Matrix", fill="black")

    for index, label in enumerate(labels):
        x = label_width + index * cell_size + 10
        y = title_height - 25
        draw.text((x, y), label[:12], fill="black")
        draw.text((20, title_height + index * cell_size + 35), label, fill="black")

    for row_index, row in enumerate(confusion_matrix):
        for column_index, value in enumerate(row):
            intensity = int(255 - (value / max_value) * 180)
            color = (intensity, intensity, 255)
            x0 = label_width + column_index * cell_size
            y0 = title_height + row_index * cell_size
            x1 = x0 + cell_size
            y1 = y0 + cell_size
            draw.rectangle((x0, y0, x1, y1), fill=color, outline="black")
            draw.text((x0 + 38, y0 + 35), str(value), fill="black")

    CONFUSION_MATRIX_PATH.parent.mkdir(parents=True, exist_ok=True)
    image.save(CONFUSION_MATRIX_PATH)


def train_ann(master_dataset_path: Path = MASTER_DATASET_PATH) -> None:
    """Run the complete ANN training workflow.

    Args:
        master_dataset_path: Processed master dataset path.
    """

    random.seed(RANDOM_SEED)
    torch.manual_seed(RANDOM_SEED)

    prepared = load_prepared_dataset(master_dataset_path)
    if prepared is None:
        return

    embedding_service = EmbeddingService()
    embedding_dimension = verify_embedding_model(embedding_service)
    if embedding_dimension is None:
        print("Training stopped because embeddings are unavailable or invalid.")
        return

    train_tensors = generate_tensors(
        prepared.train_samples,
        embedding_service,
        split_name="training",
    )
    validation_tensors = generate_tensors(
        prepared.validation_samples,
        embedding_service,
        split_name="validation",
    )
    if train_tensors is None or validation_tensors is None:
        print("Training stopped because embeddings are unavailable or invalid.")
        return

    train_features, train_labels = train_tensors
    validation_features, validation_labels = validation_tensors
    print(f"number of embeddings generated: {train_features.size(0) + validation_features.size(0)}")
    print(
        "embedding tensor shape: "
        f"train={tuple(train_features.shape)}, validation={tuple(validation_features.shape)}"
    )
    if train_features.size(1) != validation_features.size(1):
        print("Training stopped because train and validation embeddings differ in dimension.")
        return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = SentenceClassifierANN(input_dim=train_features.size(1)).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
    loss_fn = nn.CrossEntropyLoss()
    train_loader = create_data_loader(train_features, train_labels, shuffle=True)
    validation_loader = create_data_loader(validation_features, validation_labels, shuffle=False)
    print("Starting ANN training.")

    best_validation_loss = float("inf")
    best_state: dict[str, torch.Tensor] | None = None
    best_confusion_matrix: list[list[int]] = []
    best_metrics: dict[str, float | list[list[int]]] | None = None
    metrics_history: list[dict[str, Any]] = []
    epochs_without_improvement = 0

    for epoch in range(1, EPOCHS + 1):
        train_loss, _ = run_epoch(model, train_loader, loss_fn, device, optimizer)
        validation_loss, validation_metrics = run_epoch(
            model,
            validation_loader,
            loss_fn,
            device,
        )

        epoch_metrics = {
            "epoch": epoch,
            "training_loss": train_loss,
            "validation_loss": validation_loss,
            "accuracy": validation_metrics["accuracy"],
            "precision": validation_metrics["precision"],
            "recall": validation_metrics["recall"],
            "f1": validation_metrics["f1"],
        }
        metrics_history.append(epoch_metrics)

        print(
            "Epoch {epoch:02d} | Training Loss: {training_loss:.4f} | "
            "Validation Loss: {validation_loss:.4f} | Accuracy: {accuracy:.4f} | "
            "Precision: {precision:.4f} | Recall: {recall:.4f} | F1: {f1:.4f}".format(
                **epoch_metrics
            )
        )

        if validation_loss < best_validation_loss:
            best_validation_loss = validation_loss
            best_state = {
                key: value.detach().cpu().clone()
                for key, value in model.state_dict().items()
            }
            best_confusion_matrix = validation_metrics["confusion_matrix"]  # type: ignore[assignment]
            best_metrics = validation_metrics
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= PATIENCE:
            print(f"Early stopping triggered after {epoch} epochs.")
            break

    if best_state is None:
        print("No best model state was produced; nothing was saved.")
        return

    model.load_state_dict(best_state)
    save_training_outputs(
        model=model,
        label_mapping=prepared.label_mapping,
        metrics_history=metrics_history,
        confusion_matrix=best_confusion_matrix,
    )
    if best_metrics is not None:
        print("Final metrics")
        print(f"Accuracy: {best_metrics['accuracy']:.4f}")
        print(f"Precision: {best_metrics['precision']:.4f}")
        print(f"Recall: {best_metrics['recall']:.4f}")
        print(f"F1 Score: {best_metrics['f1']:.4f}")
    print(f"Best model saved to: {BEST_MODEL_PATH}")
    print(f"Label mapping saved to: {LABEL_MAPPING_PATH}")
    print(f"Training metrics saved to: {TRAINING_METRICS_PATH}")
    print(f"Confusion matrix saved to: {CONFUSION_MATRIX_PATH}")


def main() -> None:
    """Command-line entry point for ANN training."""

    train_ann()


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    main()
