"""DOCX export for professional Minutes of Meeting documents."""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from summarization.base_summarizer import MeetingAnalysisResult

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_EXPORT_DIR = PROJECT_ROOT / "exports" / "generated"

HEADING_BLUE = RGBColor(46, 116, 181)
DARK_BLUE = RGBColor(31, 77, 120)
LIGHT_GRAY = "F2F4F7"
BORDER_GRAY = "D9E2EC"
TABLE_WIDTH_DXA = 9360


def export_to_docx(
    analysis: MeetingAnalysisResult | dict[str, Any],
    *,
    output_path: str | Path | None = None,
    output_dir: str | Path = DEFAULT_EXPORT_DIR,
    meeting_info: dict[str, str] | None = None,
) -> Path:
    """Create a concise Minutes of Meeting DOCX and return its file path."""
    payload = _analysis_to_dict(analysis)
    export_path = _resolve_output_path(output_path, output_dir)
    export_path.parent.mkdir(parents=True, exist_ok=True)

    document = Document()
    _configure_document(document)
    _add_mom_title_block(document, payload, meeting_info=meeting_info)
    _add_executive_summary(document, payload)
    _add_concise_key_discussion_points(document, payload)
    _add_concise_decisions(document, payload)
    _add_action_items(document, payload)
    _add_next_meeting(document, payload, meeting_info=meeting_info)
    _add_end_marker(document)

    document.save(export_path)
    return export_path


def export_transcript_to_docx(
    analysis: MeetingAnalysisResult | dict[str, Any],
    *,
    output_path: str | Path | None = None,
    output_dir: str | Path = DEFAULT_EXPORT_DIR,
    meeting_info: dict[str, str] | None = None,
) -> Path:
    """Create a standalone cleaned transcript DOCX and return its file path."""
    payload = _analysis_to_dict(analysis)
    export_path = _resolve_transcript_output_path(output_path, output_dir, "docx")
    export_path.parent.mkdir(parents=True, exist_ok=True)

    document = Document()
    _configure_document(document)
    _add_transcript_title_block(document, payload, meeting_info=meeting_info)
    _add_cleaned_transcript(document, payload)

    document.save(export_path)
    return export_path


def _analysis_to_dict(
    analysis: MeetingAnalysisResult | dict[str, Any],
) -> dict[str, Any]:
    if isinstance(analysis, MeetingAnalysisResult):
        return analysis.to_dict()
    return analysis


def _resolve_output_path(
    output_path: str | Path | None,
    output_dir: str | Path,
) -> Path:
    if output_path is not None:
        return Path(output_path)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return Path(output_dir) / f"minutes_of_meeting_{timestamp}.docx"


def _resolve_transcript_output_path(
    output_path: str | Path | None,
    output_dir: str | Path,
    extension: str,
) -> Path:
    if output_path is not None:
        return Path(output_path)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return Path(output_dir) / f"transcript_report_{timestamp}.{extension}"


def _configure_document(document: Document) -> None:
    section = document.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    section.header_distance = Inches(0.492)
    section.footer_distance = Inches(0.492)
    section.start_type = WD_SECTION.NEW_PAGE

    styles = document.styles
    normal = styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)
    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = 1.10

    for style_name, size, color in (
        ("Heading 1", 16, HEADING_BLUE),
        ("Heading 2", 13, HEADING_BLUE),
        ("Heading 3", 12, DARK_BLUE),
    ):
        style = styles[style_name]
        style.font.name = "Calibri"
        style.font.size = Pt(size)
        style.font.color.rgb = color
        style.font.bold = True
        style.paragraph_format.space_before = Pt(12)
        style.paragraph_format.space_after = Pt(6)

    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    footer_run = footer.add_run("Generated by MeetScribe")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(102, 112, 133)


def _add_mom_title_block(
    document: Document,
    payload: dict[str, Any],
    *,
    meeting_info: dict[str, str] | None,
) -> None:
    title = (
        (meeting_info or {}).get("Meeting Title")
        or payload.get("summary", {}).get("title")
        or "Meeting"
    )

    heading = document.add_paragraph()
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    heading.paragraph_format.space_after = Pt(10)
    run = heading.add_run("MeetScribe | Minutes of Meeting")
    run.bold = True
    run.font.name = "Calibri"
    run.font.size = Pt(18)
    run.font.color.rgb = RGBColor(11, 37, 69)

    _add_horizontal_rule(document)

    title_paragraph = document.add_paragraph()
    title_paragraph.paragraph_format.space_after = Pt(2)
    title_run = title_paragraph.add_run(str(title))
    title_run.bold = True
    title_run.font.name = "Calibri"
    title_run.font.size = Pt(14)
    title_run.font.color.rgb = DARK_BLUE

    _add_compact_meeting_information(document, payload, meeting_info=meeting_info)


def _add_transcript_title_block(
    document: Document,
    payload: dict[str, Any],
    *,
    meeting_info: dict[str, str] | None,
) -> None:
    title = payload.get("summary", {}).get("title") or "Minutes of Meeting"
    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
    paragraph.paragraph_format.space_after = Pt(4)
    run = paragraph.add_run(str(title))
    run.bold = True
    run.font.name = "Calibri"
    run.font.size = Pt(22)
    run.font.color.rgb = RGBColor(11, 37, 69)

    subtitle = document.add_paragraph()
    subtitle.paragraph_format.space_after = Pt(12)
    subtitle_run = subtitle.add_run("Transcript Report")
    subtitle_run.font.size = Pt(11)
    subtitle_run.font.color.rgb = RGBColor(102, 112, 133)

    if meeting_info and meeting_info.get("Source File"):
        source = document.add_paragraph()
        source.add_run("Source Audio File: ").bold = True
        source.add_run(meeting_info["Source File"])


def _add_meeting_information(
    document: Document,
    *,
    meeting_info: dict[str, str] | None,
) -> None:
    document.add_heading("Meeting Information", level=1)
    info = {
        "Generated On": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "Prepared By": "MeetScribe",
    }
    if meeting_info:
        info.update({key: value for key, value in meeting_info.items() if value})

    table = document.add_table(rows=1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    table.style = "Table Grid"
    _shade_row(table.rows[0], LIGHT_GRAY)

    header_cells = table.rows[0].cells
    header_cells[0].text = "Field"
    header_cells[1].text = "Value"
    _format_table_row(table.rows[0], bold=True)

    for key, value in info.items():
        row = table.add_row()
        row.cells[0].text = key
        row.cells[1].text = value
        _format_table_row(row)

    _set_table_geometry(table, [2200, TABLE_WIDTH_DXA - 2200])


def _add_compact_meeting_information(
    document: Document,
    payload: dict[str, Any],
    *,
    meeting_info: dict[str, str] | None,
) -> None:
    _add_section_heading(document, "Meeting Information")
    metadata = _meeting_metadata(payload, meeting_info=meeting_info)
    table = document.add_table(rows=0, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    table.style = "Table Grid"

    for key, value in metadata.items():
        row = table.add_row()
        row.cells[0].text = key
        row.cells[1].text = value
        _format_table_row(row, bold=False)

    _set_table_geometry(table, [2500, TABLE_WIDTH_DXA - 2500])


def _add_summary_sections(document: Document, payload: dict[str, Any]) -> None:
    summary = payload.get("summary", {})
    document.add_heading("Executive Summary", level=1)
    document.add_paragraph(str(summary.get("short_summary", "")).strip() or "N/A")

    document.add_heading("Detailed Summary", level=1)
    document.add_paragraph(str(summary.get("detailed_summary", "")).strip() or "N/A")


def _add_executive_summary(document: Document, payload: dict[str, Any]) -> None:
    _add_section_heading(document, "EXECUTIVE SUMMARY")
    for paragraph_text in _executive_summary_paragraphs(payload):
        document.add_paragraph(paragraph_text)


def _add_topics(document: Document, payload: dict[str, Any]) -> None:
    document.add_heading("Topics Discussed", level=1)
    topics = payload.get("summary", {}).get("topics_discussed", [])
    _add_bullets(document, topics)


def _add_concise_topics(document: Document, payload: dict[str, Any]) -> None:
    _add_section_heading(document, "TOPICS DISCUSSED")
    topics = payload.get("summary", {}).get("topics_discussed", [])
    if not topics:
        document.add_paragraph("No topics were extracted.")
        return

    for topic in topics[:8]:
        document.add_paragraph(str(topic).strip(), style="List Bullet")


def _add_key_discussion_points(document: Document, payload: dict[str, Any]) -> None:
    document.add_heading("Key Discussion Points", level=1)
    points = payload.get("key_discussion_points", [])
    if not points:
        document.add_paragraph("No key discussion points were extracted.")
        return

    for item in points:
        timestamp = item.get("timestamp") or "N/A"
        speakers = ", ".join(item.get("speakers") or []) or "N/A"
        paragraph = document.add_paragraph(style="List Bullet")
        paragraph.add_run(f"[{timestamp}] ").bold = True
        paragraph.add_run(str(item.get("point", "")).strip())
        paragraph.add_run(f" ({speakers})").italic = True


def _add_concise_key_discussion_points(
    document: Document,
    payload: dict[str, Any],
) -> None:
    _add_section_heading(document, "KEY DISCUSSION POINTS")
    points = _dedupe_dict_items(payload.get("key_discussion_points", []), "point")[:5]
    if not points:
        document.add_paragraph("No key discussion points were extracted.")
        return

    for item in points:
        paragraph = document.add_paragraph(style="List Bullet")
        paragraph.add_run(str(item.get("point", "")).strip()).bold = True
        timestamp = item.get("timestamp") or "N/A"
        speakers = ", ".join(item.get("speakers") or []) or "N/A"
        meta = document.add_paragraph()
        meta.paragraph_format.left_indent = Inches(0.32)
        meta.paragraph_format.space_after = Pt(3)
        run = meta.add_run(f"Timestamp: {timestamp} | Speaker(s): {speakers}")
        run.italic = True
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(102, 112, 133)


def _add_decisions(document: Document, payload: dict[str, Any]) -> None:
    document.add_heading("Decisions", level=1)
    decisions = payload.get("decisions", [])
    if not decisions:
        document.add_paragraph("No decisions were extracted.")
        return

    for item in decisions:
        timestamp = item.get("timestamp") or "N/A"
        owner = item.get("owner") or "Unassigned"
        confidence = item.get("confidence") or "N/A"
        paragraph = document.add_paragraph(style="List Bullet")
        paragraph.add_run(f"[{timestamp}] ").bold = True
        paragraph.add_run(str(item.get("decision", "")).strip())
        paragraph.add_run(f" Owner: {owner}; confidence: {confidence}.").italic = True


def _add_concise_decisions(document: Document, payload: dict[str, Any]) -> None:
    _add_section_heading(document, "DECISIONS TAKEN")
    decisions = _dedupe_dict_items(payload.get("decisions", []), "decision")[:5]
    if not decisions:
        document.add_paragraph("No decisions were extracted.")
        return

    for item in decisions:
        paragraph = document.add_paragraph(style="List Number")
        paragraph.add_run(_professionalize_sentence(item.get("decision", ""))).bold = False


def _add_action_items(document: Document, payload: dict[str, Any]) -> None:
    _add_section_heading(document, "ACTION ITEMS")
    action_items = _dedupe_dict_items(payload.get("action_items", []), "task")[:7]
    if not action_items:
        document.add_paragraph("No action items were extracted.")
        return

    table = document.add_table(rows=1, cols=5)
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    table.style = "Table Grid"
    _shade_row(table.rows[0], LIGHT_GRAY)

    headers = ["Task", "Owner", "Due Date", "Priority", "Status"]
    for cell, header in zip(table.rows[0].cells, headers):
        cell.text = header
    _format_table_row(table.rows[0], bold=True)

    for item in action_items:
        row = table.add_row()
        values = [
            item.get("task") or "",
            item.get("owner") or "Unassigned",
            item.get("due_date") or "N/A",
            _priority_for_action_item(item),
            item.get("status") or "N/A",
        ]
        for cell, value in zip(row.cells, values):
            cell.text = str(value)
        _format_table_row(row)

    _set_table_geometry(table, [3500, 1400, 1300, 1200, 1960])


def _add_next_steps(document: Document, payload: dict[str, Any]) -> None:
    _add_section_heading(document, "NEXT STEPS")
    action_items = payload.get("action_items", [])
    decisions = payload.get("decisions", [])
    if not action_items and not decisions:
        document.add_paragraph("No next steps were identified.")
        return

    for item in action_items:
        sentence = _next_step_sentence(item)
        document.add_paragraph(sentence, style="List Bullet")
    for item in decisions[:3]:
        decision = _professionalize_sentence(item.get("decision", "")).rstrip(".")
        if decision:
            document.add_paragraph(f"Team will proceed in line with: {decision}.", style="List Bullet")


def _add_next_meeting(
    document: Document,
    payload: dict[str, Any],
    *,
    meeting_info: dict[str, str] | None,
) -> None:
    next_meeting = _next_meeting_text(payload, meeting_info=meeting_info)
    if not next_meeting:
        return
    _add_section_heading(document, "NEXT MEETING")
    for item in next_meeting[:2]:
        document.add_paragraph(item, style="List Bullet")


def _add_end_marker(document: Document) -> None:
    _add_horizontal_rule(document)
    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.space_before = Pt(8)
    run = paragraph.add_run("Generated by MeetScribe")
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(102, 112, 133)


def _add_cleaned_transcript(document: Document, payload: dict[str, Any]) -> None:
    document.add_heading("Cleaned Transcript", level=1)
    transcript = str(payload.get("cleaned_transcript", "")).strip()
    if not transcript:
        document.add_paragraph("No cleaned transcript was available.")
        return

    for block in re.split(r"\n\s*\n", transcript):
        block = block.strip()
        if not block:
            continue
        lines = block.splitlines()
        header = lines[0].strip()
        body = "\n".join(line.strip() for line in lines[1:]).strip()

        paragraph = document.add_paragraph()
        paragraph.paragraph_format.space_after = Pt(3)
        header_run = paragraph.add_run(header)
        header_run.bold = True
        header_run.font.color.rgb = DARK_BLUE
        if body:
            document.add_paragraph(body)


def _add_bullets(document: Document, items: list[Any]) -> None:
    if not items:
        document.add_paragraph("No items were extracted.")
        return

    for item in items:
        document.add_paragraph(str(item), style="List Bullet")


def _add_section_heading(document: Document, text: str) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(12)
    paragraph.paragraph_format.space_after = Pt(6)
    run = paragraph.add_run(text)
    run.bold = True
    run.font.name = "Calibri"
    run.font.size = Pt(12)
    run.font.color.rgb = HEADING_BLUE


def _add_horizontal_rule(document: Document) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(2)
    paragraph.paragraph_format.space_after = Pt(8)
    run = paragraph.add_run("_" * 78)
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(217, 226, 236)


def _meeting_metadata(
    payload: dict[str, Any],
    *,
    meeting_info: dict[str, str] | None,
) -> dict[str, str]:
    meeting_info = meeting_info or {}
    transcript = str(payload.get("cleaned_transcript", ""))
    metadata = {
        "Meeting Title": meeting_info.get("Meeting Title")
        or payload.get("summary", {}).get("title")
        or "Minutes of Meeting",
        "Date": meeting_info.get("Date")
        or meeting_info.get("Generated Date")
        or datetime.now().strftime("%Y-%m-%d"),
        "Duration": meeting_info.get("Duration") or _duration_from_transcript(transcript),
        "Participants / Attendees": meeting_info.get("Participants")
        or meeting_info.get("Attendees")
        or ", ".join(sorted(_speakers_from_transcript(transcript)))
        or "N/A",
        "Prepared By": meeting_info.get("Prepared By") or "MeetScribe",
    }
    optional_rows = {
        "Time": meeting_info.get("Time", ""),
        "Organization / Company": meeting_info.get("Organization / Company", ""),
        "Project Name": meeting_info.get("Project Name", ""),
    }
    return {**metadata, **{key: value for key, value in optional_rows.items() if value}}


def _duration_from_transcript(transcript: str) -> str:
    timestamp_ranges = re.findall(
        r"\[([0-9]{1,2}:[0-9]{2}(?::[0-9]{2})?)\s*-\s*([0-9]{1,2}:[0-9]{2}(?::[0-9]{2})?)\]",
        transcript,
    )
    if not timestamp_ranges:
        return "N/A"

    start_seconds = _timestamp_to_seconds(timestamp_ranges[0][0])
    end_seconds = _timestamp_to_seconds(timestamp_ranges[-1][1])
    if start_seconds is None or end_seconds is None or end_seconds <= start_seconds:
        return "N/A"

    total_minutes = max(1, round((end_seconds - start_seconds) / 60))
    return f"{total_minutes} min"


def _timestamp_to_seconds(value: str) -> int | None:
    parts = [int(part) for part in value.split(":")]
    if len(parts) == 2:
        minutes, seconds = parts
        return minutes * 60 + seconds
    if len(parts) == 3:
        hours, minutes, seconds = parts
        return hours * 3600 + minutes * 60 + seconds
    return None


def _speakers_from_transcript(transcript: str) -> set[str]:
    return set(re.findall(r"^(Speaker\s+\S+)", transcript, flags=re.MULTILINE))


def _executive_summary_paragraphs(payload: dict[str, Any]) -> list[str]:
    summary = payload.get("summary", {})
    detailed = _sanitize_business_text(
        str(summary.get("detailed_summary") or summary.get("short_summary") or "").strip()
    )
    short = _sanitize_business_text(str(summary.get("short_summary") or "").strip())
    decisions = payload.get("decisions", [])
    actions = payload.get("action_items", [])

    paragraphs: list[str] = []
    if detailed:
        paragraphs.append(_concise_paragraph(detailed))
    elif short:
        paragraphs.append(_concise_paragraph(short))
    else:
        paragraphs.append("The meeting covered the listed agenda items and produced the outcomes captured in this report.")

    if decisions:
        decision_text = "; ".join(
            _professionalize_sentence(item.get("decision", "")).rstrip(".")
            for item in decisions[:3]
            if item.get("decision")
        )
        if decision_text:
            paragraphs.append(f"Key decisions included {decision_text}.")

    if actions:
        owners = sorted({str(item.get("owner")) for item in actions if item.get("owner")})
        owner_text = ", ".join(owners[:4]) if owners else "the assigned owners"
        paragraphs.append(
            f"Follow-up activities were assigned to {owner_text}, with progress to be tracked through the action items below."
        )

    return paragraphs[:1]


def _concise_paragraph(text: str, *, max_words: int = 85) -> str:
    words = re.split(r"\s+", text.strip())
    if len(words) <= max_words:
        return text.strip()
    return " ".join(words[:max_words]).rstrip(" ,;:") + "."


def _dedupe_dict_items(items: list[Any], key: str) -> list[dict[str, Any]]:
    deduped: list[dict[str, Any]] = []
    seen: set[str] = set()
    for item in items:
        if not isinstance(item, dict):
            continue
        normalized = _normalize_text(str(item.get(key) or ""))
        if normalized and normalized in seen:
            continue
        if normalized:
            seen.add(normalized)
        deduped.append(item)
    return deduped


def _next_meeting_text(
    payload: dict[str, Any],
    *,
    meeting_info: dict[str, str] | None,
) -> list[str]:
    meeting_info = meeting_info or {}
    explicit = meeting_info.get("Next Meeting") or meeting_info.get("Next Meeting Date")
    if explicit:
        return [explicit]

    transcript = str(payload.get("cleaned_transcript", ""))
    if not _mentions_next_meeting(transcript):
        return []
    sentences = [
        sentence.strip()
        for sentence in re.split(r"(?<=[.!?])\s+", re.sub(r"\s+", " ", transcript))
        if _mentions_next_meeting(sentence)
    ]
    return [_concise_paragraph(sentence, max_words=35) for sentence in sentences[:2]]


def _mentions_next_meeting(text: str) -> bool:
    normalized = _normalize_text(text)
    return any(
        signal in normalized
        for signal in (
            "next meeting",
            "next call",
            "follow up meeting",
            "followup meeting",
            "next review",
            "meet again",
        )
    )


def _normalize_text(value: str) -> str:
    value = re.sub(r"[^a-z0-9]+", " ", value.lower())
    return re.sub(r"\s+", " ", value).strip()


def _sanitize_business_text(text: str) -> str:
    replacements = {
        "The discussion revolves around": "The meeting addressed",
        "The discussion centered around": "The meeting addressed",
        "The discussion focused on": "The meeting focused on",
        "The conversation focused on": "The meeting focused on",
        "They talked about": "Participants reviewed",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


def _professionalize_sentence(value: Any) -> str:
    text = _sanitize_business_text(str(value or "").strip())
    if not text:
        return ""
    text = text[0].upper() + text[1:]
    if text[-1] not in ".?!":
        text += "."
    return text


def _priority_for_action_item(item: dict[str, Any]) -> str:
    text = " ".join(
        str(item.get(key) or "")
        for key in ("task", "due_date", "status")
    ).lower()
    if any(token in text for token in ("urgent", "today", "tomorrow", "blocked", "critical")):
        return "High"
    if any(token in text for token in ("this week", "friday", "next demo", "review", "validate")):
        return "Medium"
    return "Low"


def _next_step_sentence(item: dict[str, Any]) -> str:
    owner = item.get("owner") or "Team"
    task = str(item.get("task") or "complete the assigned task").rstrip(".")
    due_date = item.get("due_date")
    if due_date and str(due_date).upper() != "N/A":
        return f"{owner} will {task[0].lower() + task[1:]} by {due_date}."
    return f"{owner} will {task[0].lower() + task[1:]}."


def _format_table_row(row: Any, *, bold: bool = False) -> None:
    for cell in row.cells:
        cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        _set_cell_margins(cell)
        for paragraph in cell.paragraphs:
            paragraph.paragraph_format.space_after = Pt(0)
            for run in paragraph.runs:
                run.font.size = Pt(9.5)
                run.font.name = "Calibri"
                run.bold = bold


def _set_table_geometry(table: Any, widths_dxa: list[int]) -> None:
    table.autofit = False
    table_element = table._tbl
    table_properties = table_element.tblPr

    table_width = table_properties.find(qn("w:tblW"))
    if table_width is None:
        table_width = OxmlElement("w:tblW")
        table_properties.append(table_width)
    table_width.set(qn("w:type"), "dxa")
    table_width.set(qn("w:w"), str(sum(widths_dxa)))

    table_indent = OxmlElement("w:tblInd")
    table_indent.set(qn("w:w"), "120")
    table_indent.set(qn("w:type"), "dxa")
    table_properties.append(table_indent)

    grid = table_element.tblGrid
    if grid is None:
        grid = OxmlElement("w:tblGrid")
        table_element.insert(1, grid)
    for child in list(grid):
        grid.remove(child)
    for width in widths_dxa:
        grid_col = OxmlElement("w:gridCol")
        grid_col.set(qn("w:w"), str(width))
        grid.append(grid_col)

    for row in table.rows:
        for cell, width in zip(row.cells, widths_dxa):
            cell.width = Inches(width / 1440)
            cell_properties = cell._tc.get_or_add_tcPr()
            cell_width = cell_properties.find(qn("w:tcW"))
            if cell_width is None:
                cell_width = OxmlElement("w:tcW")
                cell_properties.append(cell_width)
            cell_width.set(qn("w:type"), "dxa")
            cell_width.set(qn("w:w"), str(width))


def _set_cell_margins(
    cell: Any,
    *,
    top: int = 80,
    bottom: int = 80,
    start: int = 120,
    end: int = 120,
) -> None:
    cell_properties = cell._tc.get_or_add_tcPr()
    margins = cell_properties.first_child_found_in("w:tcMar")
    if margins is None:
        margins = OxmlElement("w:tcMar")
        cell_properties.append(margins)

    for margin_name, value in (
        ("top", top),
        ("bottom", bottom),
        ("start", start),
        ("end", end),
    ):
        node = margins.find(qn(f"w:{margin_name}"))
        if node is None:
            node = OxmlElement(f"w:{margin_name}")
            margins.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def _shade_row(row: Any, fill: str) -> None:
    for cell in row.cells:
        cell_properties = cell._tc.get_or_add_tcPr()
        shading = OxmlElement("w:shd")
        shading.set(qn("w:fill"), fill)
        cell_properties.append(shading)
